# Generated by Django 5.1.6 on 2025-03-09 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_students', '0001_initial'),
        ('app_teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_teacher', to='app_teachers.teachers'),
        ),
    ]
