# Generated by Django 5.1.6 on 2025-03-09 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_groups', '0002_alter_groups_students_alter_groups_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('homework', models.FileField(null=True, upload_to='homeworks')),
            ],
            options={
                'verbose_name': 'homework',
                'verbose_name_plural': 'homeworks',
            },
        ),
        migrations.AlterField(
            model_name='groups',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'role': 'student'}, related_name='group_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
