# Generated by Django 5.1.6 on 2025-03-09 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_groups', '0003_homeworks_alter_groups_students'),
        ('app_teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworks',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='app_teachers.lessons'),
        ),
    ]
